version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    container_name: database-container

    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
      
  web:
    image: doerymi/yamdb_final:latest
    container_name: web-container
    restart: always

    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - static_value:/var/html/static/
      - media_value:/var/html/media/

    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    depends_on:
      - web
      - certbot

  certbot:
    image: certbot/certbot
      
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes: 
  static_value:
  media_value:
  db_data:

